


/*

/*
class MainFrame :public wxFrame
{
public:
	MainFrame(const wxString& title, const wxPoint& pos, const wxSize& size);

	void UpdateInfo(wxCommandEvent& event, WereHouse& were, wxStaticText& text);

	wxListBox* poke_list;
private:
	
};
*/
/*
class WereHouse {
public:
	//std::vector<std::vector<std::string>> werehouse;
	std::vector<std::vector<std::string>> strvec;
	
	void LoadData() {

		std::fstream file;
		file.open("PokeGenOne.txt", std::ios::in);
		std::string data;
		if (file.is_open()) {
			while (std::getline(file, data)) {
				strvec.push_back(Slash(data));
				//wxString text = GetInfo(data, 3).give();
			}
		}
		else {
			std::cout << "Error Occured while openning PokeGenOne.txt" << std::endl;;
		}
	}
	
	void Show() {
		LoadData();
		for (auto x : strvec) {
			int size = x.size();
			for (int i = 0; i < size; i++) {
				std::cout << x[i];
			}
			std::cout << "\n";
		}
	}

	std::vector<std::string> Slash(std::string data) {
		std::vector<std::string> vec;
		std::string str = data;
		std::string tmp;
		
		for (int i = 0; i < str.size(); i++) {
			if (str[i] == ',') {
				vec.push_back(tmp);
				tmp.clear();
			}
			else {
				tmp += str[i];
			}
		}
		return vec;
	}

	~WereHouse() {
		strvec.clear();
	}
};

wxIMPLEMENT_APP(MainApp);
/*

bool MainApp::OnInit()
{
	MainFrame* frame = new MainFrame("PokeDex", wxPoint(20, 30), wxSize(450, 340));
	frame->Show();
	return true;
}




void MainFrame::UpdateInfo(wxCommandEvent& event, WereHouse& were, wxStaticText& text) {
	std::string label = "PokeDex Number: ";

}
*/

/*  Reference cheatsheet
EVT_CHECKBOX(id, func):
Process a wxEVT_CHECKBOX command, which is generated by a wxCheckBox control.*/